name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint *.js

      - name: Run npm audit
        run: npm audit --audit-level=high
  test:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run tests
        run: node test.js

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push App1
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: whoamiadi/twn-app1:latest

      - name: Build and push App2
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: whoamiadi/twn-app2:latest

      - name: Build and push App3
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: whoamiadi/twn-app3:latest

  deploy:
     runs-on: ubuntu-latest
     needs: build
     steps:
       - name: Deploy to EC2
         uses: appleboy/ssh-action@v1.0.0
         with:
           host: ${{ secrets.EC2_HOST }}
           username: ${{ secrets.EC2_USER }}
           key: ${{ secrets.EC2_KEY }}
           script: |
             sudo docker pull whoamiadi/twn-app1:latest
             sudo docker pull whoamiadi/twn-app2:latest
             sudo docker pull whoamiadi/twn-app3:latest
             sudo docker stop app1 app2 app3 || true
             sudo docker rm app1 app2 app3 || true
             sudo docker run -d -p 3001:3000 -e "APP_NAME=App1" --name app1 whoamiadi/twn-app1
             sudo docker run -d -p 3002:3000 -e "APP_NAME=App2" --name app2 whoamiadi/twn-app2
             sudo docker run -d -p 3003:3000 -e "APP_NAME=App3" --name app3 whoamiadi/twn-app3
